//HintName: FeatureConstants.g.cs
// <auto-generated />
public static class FeatureConstants
{
    public const string TestFeature1 = "TestFeature1";
    public const string TestFeature2 = "TestFeature2";
}
